version: "2"
services: 
  nginx: 
    image: nginx:1.14
    ports: 
     - "80:80"
    volumes: 
     - $PWD/nginx/conf/conf.d:/etc/nginx/conf.d
     - $PWD/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
     - $PWD/nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf
     - $PWD/nginx/conf/php-fpm.conf:/etc/nginx/php-fpm.conf
     - $PWD/nginx/conf/rewrite:/etc/nginx/rewrite
     - $PWD/www:/www
     - $PWD/nginx/log:/wwwlogs
    networks: 
     - php-network
    links: 
     - "php-fpm" 
  php-fpm: 
    build: $PWD/php/.
    expose: 
     - "9000"
    networks: 
     - php-network
    volumes: 
     - $PWD/www:/www
    links: 
     - "redis"
     - "memcached"
     - "mysql"
  redis: 
    image: redis:4.0.10
    ports: 
     - "6379:6379"
    volumes: 
     - $PWD/redis/data:/data
    networks: 
     - php-network
  memcached: 
    image: memcached:1.5.9
    ports: 
     - "11211:11211"
    networks: 
     - php-network
  mysql: 
    image: mysql:5.7
    restart: always 
    ports: 
     - "3306:3306"
    volumes: 
     - $PWD/mysql/conf:/etc/mysql/conf.d
     - $PWD/mysql/logs:/logs
     - $PWD/mysql/data:/var/lib/mysql:rw
    environment:
     - MYSQL_ROOT_PASSWORD=hong;123
    networks: 
     - php-network
networks: 
  php-network: 
    driver: bridge
